Deploy Frontend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,15 +27,17 @@ commands:
       - run:
           name: Revert migrations
           # Add when this will run
+          when: on_success
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
             SUCCESS = 1
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
+            cd ~/project/backend
+            npm install
             #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+            npm run migration:revert
+            #  exit 1
             fi
             
 jobs:
@@ -267,13 +269,17 @@ jobs:
       # Checkout code from git
       - checkout
       - run:
-          name: Run migrations
+          name: Install dependencies 
           command: |
-            # Your code here
             cd backend
             sudo apt update
             sudo apt install -y awscli
-            npm install
+            npm install  
+
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
             # Run and save the migration output
             npm run migrations > migrations_dump.txt
 #            exit 1
@@ -290,29 +296,53 @@ jobs:
             fi
 #            exit 1
      # Here's where you will add some code to rollback on failure
-      - destroy-environment   
+      - destroy-environment
+      - revert-migrations
 
-  # deploy-frontend:
-  #   docker:
-  #     # Docker image here that supports AWS CLI
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     # Checkout code from git
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           # your code here
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "${API_URL}"
-  #     - run:
-  #         name: Deploy frontend objects
-  #         command: |
-  #           # your code here
-  #     # Here's where you will add some code to rollback on failure      
+  deploy-frontend:
+   docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            apk add --update nodejs npm ansible zip tar
+            pip3 install awscli
+            cd frontend
+            npm install
+            apk add bash
+            apk add --no-cache curl
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            # your code here
+            cd frontend
+            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
+            yum -y install nodejs
+            npm install -g npm
+            npm install oauth2
+            npm install webpack
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      # Here's where you will add some code to rollback on failure 
+      - destroy-environment
+      - revert-migrations      
                     
   # deploy-backend:
   #   docker:
