run migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -256,42 +256,90 @@ jobs:
 #            exit 1
       # Here's where you will add some code to rollback on failure      
 
-  run-migrations:
-    docker:
-      # Docker image here that supports NodeJS
-      - image: cimg/node:18.2.0
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies 
-          command: |
-            cd backend
-            sudo apt update
-            sudo apt install -y awscli
-            npm install  
+#   run-migrations:
+#     docker:
+#       # Docker image here that supports NodeJS
+#       - image: cimg/node:18.2.0
+#     steps:
+#       # Checkout code from git
+#       - checkout
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             cd backend
+#             sudo apt update
+#             sudo apt install -y awscli
+#             npm install
 
-      - run:
-          name: Run migrations
-          working_directory: ./backend
-          command: |
-            # Your code here
-            # Run and save the migration output
-            npm run migrations > migrations_dump.txt
-#            exit 1
-      - run:
-          name: Send migration results to memstash
-          command: |
-            # Your code here
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-            # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
-            # curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
-            curl https://kvdb.io/RjGyoa4CD28AApcpH4SgJT/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-            fi
+#       - run:
+#           name: Run migrations
+#           working_directory: ./backend
+#           command: |
+#             # Your code here
+#             # Run and save the migration output
+#             npm run migrations > migrations_dump.txt
+# #            exit 1
+#       - run:
+#           name: Send migration results to memstash
+#           command: |
+#             # Your code here
+#             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+#             then
+#             # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
+#             # curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+#             # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+#             curl https://kvdb.io/RjGyoa4CD28AApcpH4SgJT/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+#             fi
 #            exit 1
      # Here's where you will add some code to rollback on failure
+  run-migrations:
+    docker:
+      - image: cimg/node:16.13.1
+    resource_class: medium
+    steps:
+      - checkout
+      - restore_cache:
+          keys:
+            - backend-build
+      - run:
+          name: Install nvm
+          command: |
+            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
+      - run:
+          name: Run migrations
+          command: |
+            #echo NODE_ENV=production >> ~/project/backend/.env
+            echo "TYPEORM_CONNECTION = ${TYPEORM_CONNECTION}" >> ~/project/backend/.env
+            echo "TYPEORM_ENTITIES = ${TYPEORM_ENTITIES}" >> ~/project/backend/.env
+            echo "TYPEORM_HOST = ${TYPEORM_HOST}" >> ~/project/backend/.env
+            echo "TYPEORM_PORT = ${TYPEORM_PORT}" >> ~/project/backend/.env
+            echo "TYPEORM_USERNAME = ${TYPEORM_USERNAME}" >> ~/project/backend/.env
+            echo "TYPEORM_PASSWORD = ${TYPEORM_PASSWORD}" >> ~/project/backend/.env
+            echo "TYPEORM_DATABASE = ${TYPEORM_DATABASE}" >> ~/project/backend/.env
+            echo "TYPEORM_MIGRATIONS = ${TYPEORM_MIGRATIONS}" >> ~/project/backend/.env
+            echo "TYPEORM_MIGRATIONS_DIR = ${TYPEORM_MIGRATIONS_DIR}" >> ~/project/backend/.env
+            cd ~/project/backend
+            source ~/.profile
+            nvm install v13.8.0
+            npm install
+            npm run migrations > migrations_dump.txt
+      - run:
+          # It seems like memstash.io is no longer available/accessible (?)
+          name: Report migration results
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              echo "Migration succeeded for ${CIRCLE_WORKFLOW_ID:0:7}"
+              echo "1" >> ~/project/backend/migration-results.txt
+            else
+              echo "Migration failed for ${CIRCLE_WORKFLOW_ID:0:7}:"
+              cat ~/project/backend/migrations_dump.txt
+              echo "fail" >> ~/project/backend/migration-results.txt
+            fi
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/backend/migration-results.txt
       - destroy-environment:
           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
       - revert-migrations:
